### ISSUE TITLE
Finalize draft proposal for pymc-experimental

### ISSUE THREAD

**Issue by fonnesbeck** [pymc-devs/pymc-experimental#1]
I have seeded this repository with a README that is a proposal of how the repository is intended to be used by the PyMC development team. The proposal is only partially written, so you can contribute by editing and fleshing out the document and by contributing to the discussion in this issue.

**Comment by ccaprani** [comment]
Thanks @fonnesbeck - is it worth enabling the Discussion on this repo as a lower bar to...welll...discussion?!

**Comment by fonnesbeck** [comment]
Done
