### ISSUE TITLE
Fail tests with uncaught warnings 

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-experimental#102]
The earlier we start, the easier it is :)

**Comment by michaelraczycki** [comment]
do you mean to change the pytest settings to strict? Because I believe that by default pytest should fail test if it has uncaught exception

**Comment by ricardoV94** [comment]
Oh I mean uncaught warnings

**Comment by michaelraczycki** [comment]
I'd like to do it then, do you have something specific in mind? I'd just create the pytest.ini file and use "addopts = -W error" global setting, then all warnings should fail the test. Later on we can exclude specific types of warnings if need be

**Comment by ricardoV94** [comment]
According to pytest you can specify

```
[pytest]
filterwarnings =
    error
```

https://docs.pytest.org/en/7.1.x/how-to/capture-warnings.html

Yes that should be a good start.
