### ISSUE TITLE
consistent naming in model_builder.py

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-devs/pymc-experimental#109]
I wanted to propose few minor changes to increase consistency in the code. What I noticed is that all the functions are named with verbs, as usual, but then there's 'id' function. In my opinion it would be better to stick with the rest of the convention and call it 'generate_id'. Second thing is that other functions have type hinting, and in case of id function even though the comment inside the function itself contains description of what type it returns, the hinting is not added. If you agree with those changes I'll create a pull request right away

**Comment by twiecki** [comment]
Maybe we could turn `id` into a `property`?

**Comment by michaelraczycki** [comment]
If you mean @property decorator, then it would also work as well, the only problem I have with those is that if the function is meant to be used also outside o this very file, it creates confusion. Not everyone will know that it's a a function, and from code perspective it will look like a variable.

**Comment by twiecki** [comment]
yeah, `@property` but note that this is part of the internal API anyway.

**Comment by michaelraczycki** [comment]
In this case I'll create new PR to change it to @property
