### ISSUE TITLE
Change ModelBuilder model_config and sample_config saving to JSON

### ISSUE THREAD

**Issue by lemartinet** [pymc-devs/pymc-experimental#120]
Hi!

Due to how model_config is serialized when saving a ModelBuilder object, it only works with flat dictionaries. In my use case, I'm describing model configuration through a more nested structure, .e.g. with dict being used as value of a key.
One potential solution to support this could be to turn the model_config into a string using json. 
I'm not familiar with the hashing mechanism, but using nested dicts might also impact this part of the code

Thanks!
Manu

**Comment by twiecki** [comment]
I agree that would be better. CC @michaelraczycki
