### ISSUE TITLE
Can't find on PIP

### ISSUE THREAD

**Issue by mattiasthalen** [pymc-devs/pymc-experimental#126]
I'm trying to install `pymc-experimental` to gain access to the `ModelBuilder`.

I'm following the notebook [Using ModelBuilder class for deploying PyMC models](https://www.pymc.io/projects/examples/en/latest/howto/model_builder.html) and it says to install using `pip install pymc-experimental`, but that just throws the following error:
```
ERROR: Could not find a version that satisfies the requirement pymc-experimental (from versions: none)
ERROR: No matching distribution found for pymc-experimental
```

**Platform:** Apple M1
**OS:** macOs Ventura 13.2.1 (22D68)

**Comment by ricardoV94** [comment]
I don't think we have released it yet! You should be able to install via github by

```bash
pip install git+https://github.com/pymc-devs/pymc-experimental.git
```

**Comment by mattiasthalen** [comment]
Ah ok, not sure if the linked article should be updated with this.
Either way, it worked. Thanks!

**Comment by ricardoV94** [comment]
Thanks for the report, we will try to release soon
