### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-experimental#129]
Users are confused that they can't install via pip #127 , we should just push a version to pypi.

**Comment by ricardoV94** [comment]
I don't think we have an automated release pipeline yet though

**Comment by ricardoV94** [comment]
CC @lucianopaz @tomicapretto do you happen to have time/interest to set it up?

**Comment by michaelraczycki** [comment]
If it's not super urgent then I could take a look at it, potentially learn how to set it up (I never did this, but happy to learn)
Of course if you have some tips on where to start, they're all highly appreciated

**Comment by michaelraczycki** [comment]
https://pypi.org/project/pymc-experimental/0.0.2/
It's available now, would you like me to prepare release.yml as well?

**Comment by michaelraczycki** [comment]
done in #134

**Comment by ricardoV94** [comment]
We haven't actually cut a release yet

**Comment by ricardoV94** [comment]
The issue was a release was done without doing a github release (which I missed). 
I did one in the meantime. Closing this issue again!
