### ISSUE TITLE
Implement a CorrCholesky transformation for LKJCorr

### ISSUE THREAD

**Issue by junpenglao** [pymc-devs/pymc-experimental#13]
Came across this issue in TFP: https://github.com/tensorflow/probability/issues/400 and found out that our transformation of LKJ is just a interval transformation - that's incorrect as it will produce invalid correlation matrix right? 
https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L1158-L1159

**Comment by ricardoV94** [comment]
Closing in favor of https://github.com/pymc-devs/pymc/issues/7101
