### ISSUE TITLE
Model Builder broken by recent PyMC changes

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymc-experimental#130]
@Monsurat-Onabajo and @BerylKanali discovered that marginal_model.py has this import statement:

```python
from pymc.logprob.basic import factorized_joint_logprob
```

Which has been broken by [this](https://github.com/pymc-devs/pymc/pull/6599).

**Comment by ricardoV94** [comment]
This was just fixed in https://github.com/pymc-devs/pymc-experimental/pull/124

Needs pymc 5.2.0

**Comment by cluhmann** [comment]
@ricardoV94 You're too fast!

**Comment by ricardoV94** [comment]
Can I close this issue @cluhmann ?
