### ISSUE TITLE
pytest fails locally

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-devs/pymc-experimental#132]
After pulling latest version of main, suddenly I can't run tests locally, after using

`pytest tests/test_model_builder.py` 
Im getting :
________________________________________________________________ ERROR collecting pymc_experimental/tests/test_model_builder.py ________________________________________________________________
ImportError while importing test module '/Users/michalraczycki/Documents/pymc-experimental/pymc-experimental/pymc_experimental/tests/test_model_builder.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
__init__.py:31: in <module>
    from pymc_experimental.marginal_model import MarginalModel
marginal_model.py:10: in <module>
    from pymc.logprob.basic import factorized_joint_logprob
E   ModuleNotFoundError: No module named 'pymc.logprob.basic'

@ricardoV94, @twiecki  any suggestions on how to fix it?

**Comment by ricardoV94** [comment]
Update to pymc 5.2.0

**Comment by michaelraczycki** [comment]
Thanks! it worked like a charm :)
