### ISSUE TITLE
Incorrect `PGBART.stats_dtypes` annotation

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/pymc-experimental#16]
## Description of your problem

The [`BlockedStep.stats_dtypes` ](https://github.com/pymc-devs/pymc/blob/v4.0.0b2/pymc/step_methods/arraystep.py#L53) should map stat names to NumPy dtypes.
Note that this also applies to arrays and we should probably introduce a `BlockedStep.stats_shapes` to account for their shape (related to step method refactoring).

But mypy revealed that [`PGBART.stats_dtypes`](https://github.com/pymc-devs/pymc/blob/v4.0.0b2/pymc/bart/pgbart.py#L56) incorrectly maps to `type`.

I determined that it should be `"variable_inclusion": np.int64`, but for the `"bart_trees"` I was unable to determine the dtype from reading the code.

@aloctavodia can you take care of this?

**Comment by aloctavodia** [comment]
Maybe this is a good time to discuss how we store these sample stats (see also #14 for some issues arising from the migration to this repo). One problem with `bart_trees` is that they can easily eat a lot of memory, for each posterior sample we save "m" trees (with "m" usually between 50 and 200). So we have m * chain * draw trees in total in an InferenceData.

**Comment by michaelosthege** [comment]
> But for "variable_inclusion" changing it to np.int64 instead of np.ndarray will lead to an error.

Something other than int64 then? Memory pre-allocation code will do something like `np.empty((draws,), dtype=np.dtype(stat_dtype))` and `ndarray` automatically becomes that same as `np.dtype(object)`.

> For "bart_trees" we can use object.

Yes, that'll work:
```python
np.empty((3,), dtype=np.dtype(object))
>>> array([None, None, None], dtype=object)
```

Pre-allocation requires known, static shapes and non-object dtypes, **which are currently not delivered by PyMC**, but the `mcbackend.NumPyChain` doesn't make a difference between draws & stats:
https://github.com/michaelosthege/mcbackend/blob/ba995103034f2b04aed2429ba79eebd4812db2e3/mcbackend/backends/numpy.py#L62-L74

Similarly when they're appended:
https://github.com/michaelosthege/mcbackend/blob/ba995103034f2b04aed2429ba79eebd4812db2e3/mcbackend/backends/numpy.py#L81-L83

> for each posterior sample we save "m" trees

I can see how that blows up memory, but the stats API is probably still the best mechanism to handle it.
You could also store them thinned if you don't need every iteration.
The `pymc.backends.ndarray.NDArray` backend, but also `mcbackend.NumPyChain` and `mcbackend.ClickHouseChain` can handle that. Not sure if it's tested, but those are just `None` entries in a list or `object`-`ndarray`.
