### ISSUE TITLE
Cannot compile GeneralizedPoisson model

### ISSUE THREAD

**Issue by jaharvey8** [pymc-devs/pymc-experimental#169]
Looks like maybe a new version of pytensor broke the GeneralizedPoisson distribution. Until recently I used to be able to use the generalized poisson distribution as a likelihood just fine. Now when I run pm.sample I get a lot of these types of errors

ERROR (pytensor.graph.rewriting.basic): Rewrite failure due to: constant_folding
ERROR (pytensor.graph.rewriting.basic): node: Elemwise{erfcx,no_inplace}(TensorConstant{-7.071067932881649})
ERROR (pytensor.graph.rewriting.basic): TRACEBACK:
ERROR (pytensor.graph.rewriting.basic): Traceback (most recent call last):

Later it mentions a missing file in the pytensor package

[Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/pytensor/scalar/c_code/Faddeeva.cc'

**Comment by ricardoV94** [comment]
This is due to an error with the last pytensor release. The issue will be fixed here: https://github.com/pymc-devs/pytensor/pull/310

In the meantime you can ask to install an older version of PyTensor.
