### ISSUE TITLE
fix test_random_draws flakiness

### ISSUE THREAD

**Issue by michaelraczycki** [pymc-devs/pymc-experimental#192]
[https://github.com/pymc-devs/pymc-experimental/actions/runs/5228903518/jobs/9441547331?pr=191](url)

Recent changes in pymc and logprob submodule has caused the test to become flaky. Probably the solution is to add random seed to the test.

**Comment by ricardoV94** [comment]
The changes are unrelated, the test is/should be as flaky as it was before
