### ISSUE TITLE
Skellam Distribution Support

### ISSUE THREAD

**Issue by zzzrbx** [pymc-devs/pymc-experimental#197]
### Context for the issue:

Hello,
is there a plan to support the Skellam distribution?

Thank you,

**Comment by ricardoV94** [comment]
> I'll take this one as well. Seems like the CustomDist wrapper would be way to go here too?

Yup same vibe

**Comment by ricardoV94** [comment]
> I'll take this one as well. Seems like the CustomDist wrapper would be way to go here too?

Yup, same vibe

**Comment by wd60622** [comment]
I'll take this one as well. Seems like the CustomDist wrapper would be way to go here too?
