### ISSUE TITLE
Question: Will the do-operator be available for ModelBuilder?

### ISSUE THREAD

**Issue by galenseilis** [pymc-devs/pymc-experimental#236]
I'm excited about the existence of the do-operator being incorporated into PyMC:
- https://www.pymc.io/projects/examples/en/latest/causal_inference/interventional_distribution.html
- https://drbenvincent.github.io/posts/causal_fear.html

I'm considering whether to use ModelBuilder for some custom model classes that are scikit-learn-like that *also* have the do-operator available.

If I start developing model classes with ModelBuilder can I expect that the do-operator will be available for them?

**Comment by ricardoV94** [comment]
The do operator works at the pymc Model level by returning a modified copy of the model.

I am sure you can make use of if with the ModelBuilder, just have to think what exactly you want to do.
