### ISSUE TITLE
ENH: Beta negative binomial distribution

### ISSUE THREAD

**Issue by ferrine** [pymc-devs/pymc-experimental#247]
### Before

There is no such a distribution that represents [Beta Negative Binomial](https://en.wikipedia.org/wiki/Beta_negative_binomial_distribution) distribution.

> The beta negative binomial is non-identifiable which can be seen easily by simply swapping $r$ and 
$\beta$ in the above density or characteristic function and noting that it is unchanged. Thus estimation demands that a constraint be placed on $r$, 
$\beta$ or both.

### After

```python
with pm.Model() as model:
    pm.BetaNegativeBinomial("bnb", alpha=alpha, beta=1, r=r)
```

**Comment by wd60622** [comment]
There seems to be pr on scipy.stats (will link)
But the sampling step might not be the difficult point and doesn't need to be bottleneck
I can give it a try without waiting for scipy
