### ISSUE TITLE
Implement Maxwell-Boltzmann distribution helper

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-experimental#259]
See https://github.com/pymc-devs/pymc/blob/ec4407d3db2c8ebe77e62c65f2eda3f5703e6279/tests/distributions/test_continuous.py#L994-L1021

We already implemented the `Chi` in #239

**Comment by wd60622** [comment]
Does @twiecki still want to implement?

**Comment by ricardoV94** [comment]
> Does @twiecki still want to implement?

I don't remember any disagreement about implementing it, just how it should be done. Feel free to take a stab at it

**Comment by ricardoV94** [comment]
Closed via #241
