### ISSUE TITLE
`TimeSeasonality` component of statespace module lists wrong dimensions

### ISSUE THREAD

**Issue by kforeman** [pymc-devs/pymc-experimental#262]
If you create a structural timeseries model with a `TimeSeasonality` component, it says the corresponding coefficients should have dim `{name}_state`, but should actually be `{name}_periods`.

```python
ws = st.TimeSeasonality(
    season_length=7,  # day of week
    name="weekly",
    innovations=True,
    state_names=["Mon", "Tue", "Wed", "Thur", "Fri", "Sat", "Sun"],
)
sts_mod = (ws).build()
```

says:
```
The following parameters should be assigned priors inside a PyMC model block: 
	weekly_coefs -- shape: (6,), constraints: None, dims: (weekly_state, )
	sigma_weekly -- shape: (1,), constraints: Positive, dims: None
	P0 -- shape: (6, 6), constraints: Positive semi-definite, dims: ('state', 'state_aux')
```

However, if you use `weekly_state` as the dim, it throws an error:
```python
with pm.Model(coords=sts_mod.coords) as mod:
    weekly_coefs = pm.Normal("weekly-coefs", mu=0, sigma=1, dims=("weekly_state",))
```
returns
```
KeyError: "Dimensions {'weekly_state'} are unknown to the model and cannot be used to specify a `shape`."
```

Changing instead to `weekly_periods` fixes it:
```python
with pm.Model(coords=sts_mod.coords) as mod:
    weekly_coefs = pm.Normal("weekly-coefs", mu=0, sigma=1, dims=("weekly_periods",))
```

I thought maybe this was arising from [this line](https://github.com/pymc-devs/pymc-experimental/blob/40e28e85516785e26cabfb9051bbc487793a399d/pymc_experimental/statespace/models/structural.py#L1121) but `sts_mod.param_dims` correctly returns `{'weekly_coefs': ('weekly_periods',), 'P0': ('state', 'state_aux')}` in this case, so I suppose I'm not quite sure exactly how the recordkeeping for dims works.

**Comment by jessegrabowski** [comment]
Ah yes there's a typo somewhere in the codebase. I have actually run into this myself, but I will push a fix ASAP.
