### ISSUE TITLE
KarhunenLoeveExpansion raises import error

### ISSUE THREAD

**Issue by HasnainRaz** [pymc-devs/pymc-experimental#263]
Using pymc==5.9.1

https://github.com/pymc-devs/pymc-experimental/blob/main/pymc_experimental/gp/latent_approx.py#L130C15-L130C15

raises import error on `pm.gp.util.cholesky` and `pm.gp.util.stabilize`

It seems it just needs to be:
`cholesky` and `stabilize` since they are imported already correctly in the module.

**Comment by ricardoV94** [comment]
Sounds about right @HasnainRaz, would you mind opening a Pull request to fix it?

**Comment by HasnainRaz** [comment]
@ricardoV94 I tried but it seems I don't have the authorization. Am I missing something?

**Comment by ricardoV94** [comment]
Yes you need to fork the repo and open a pull request after you did changes on your fork: https://www.pymc.io/projects/docs/en/latest/contributing/pr_tutorial.html
