### ISSUE TITLE
Forcasting out-of-sample discrete_markov_chain.ipynb

### ISSUE THREAD

**Issue by NicoGreggio** [pymc-devs/pymc-experimental#264]
Hi everyone!! 👍 
I am trying to do a quick out-of-sample forcasting on the example of the markov switching autoregressive model. I would like to calculate a forecast year from the last historical data.
Can anyone help me/has anyone done anything yet? Thanks in advance!

Nicolò

**Comment by ricardoV94** [comment]
@NicoGreggio could you share this question as a topic in our Discourse? https://discourse.pymc.io/

We keep github for development issues. Besides, an answer on discourse will be more useful for other users as it is more discoverable. Feel free to ping @jessegrabowski in the discourse, I'm sure he has a reply at the tip of his fingertips
