### ISSUE TITLE
`test_histogram_approximation` failing due to warning in newer JAX release

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/pymc-experimental#305]
https://github.com/pymc-devs/pymc-experimental/actions/runs/7842985013/job/21402357791?pr=304#step:7:2388

**Comment by jessegrabowski** [comment]
Appears to be due to https://github.com/google/jax/pull/18989

**Comment by ricardoV94** [comment]
Is the histogram functionality using JAX @ferrine? We may need to redesign if that's the case because it can't be use with PyMC multiprocessing in that case

**Comment by jessegrabowski** [comment]
I think it's related to `pm.sample`, not histogram. There are test in `test_linear_model` and `test_model_builder` that are also failing because they call `pm.sample`

**Comment by ricardoV94** [comment]
So what if JAX is loaded it will issue a warning on `os.fork` even if it's not being used?

**Comment by ricardoV94** [comment]
Then let's just ignore the warning, it's stupid
