### ISSUE TITLE
Broken CI 

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/pymc-experimental#76]
`The workflow is not valid. .github/workflows/test.yml (Line: 22, Col: 22): Unexpected value 'pymc-experimental/tests' .github/workflows/test.yml (Line: 84, Col: 22): Unexpected value 'pymc-experimental/tests'`

This is from https://github.com/pymc-devs/pymc-experimental/pull/72

**Comment by ricardoV94** [comment]
@twiecki is this fixed?
