### ISSUE TITLE
pytest is checking the docstrings too when passed on windows

### ISSUE THREAD

**Issue by 5hv5hvnk** [pymc-devs/pymc-experimental#81]
I believe we should not pass `--doctest-modules` in here, because of this even the doc string from code is passed and throws errors.

https://github.com/pymc-devs/pymc-experimental/blob/14e24063a9da3a624dff2e5c84528dedf7e522fe/.github/workflows/test.yml#L134

**Comment by ferrine** [comment]
The CI is doing good job testing code samples in documentation

**Comment by 5hv5hvnk** [comment]
The same should be applied to line executing on ubuntu then, since it misses the parameter there.
https://github.com/pymc-devs/pymc-experimental/blob/14e24063a9da3a624dff2e5c84528dedf7e522fe/.github/workflows/test.yml#L71
